# 타이타닉 탑승객 정보 --> 생존 여부 예측

## 라이브러리 불러오기

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

## 데이터 가져오기 - seaborn 데이터셋

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## 결측치

In [4]:
df.isnull().sum() # 컬럼별로 결측치 수를 파악

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

## 생존 비율

In [6]:
df['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

## feature (입력값)

In [7]:
features = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare']

## label (정답, target) --> 'survived'

## label(target) + features --> 새로운 데이터프레임

## label(target) + features --> 새로운 데이터 프레임 df_model

In [8]:
df_model = df[features + ['survived']].copy()
df_model.head()

   pclass     sex   age  sibsp  parch     fare  survived
0       3    male  22.0      1      0   7.2500         0
1       1  female  38.0      1      0  71.2833         1
2       3  female  26.0      0      0   7.9250         1
3       1  female  35.0      1      0  53.1000         1
4       3    male  35.0      0      0   8.0500         0

In [9]:
df_model.shape

(891, 7)

## 결측치 처리 -> fillna() --> 중간값을 채울거다!

In [10]:
df_model['age'].fillna(df_model['age'].median())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [11]:
df_model['age'] = df_model['age'].fillna(df_model['age'].median())

In [12]:
df_model.isnull().sum()

pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
survived    0
dtype: int64

In [13]:
df_model.head(10)

   pclass     sex   age  sibsp  parch     fare  survived
0       3    male  22.0      1      0   7.2500         0
1       1  female  38.0      1      0  71.2833         1
2       3  female  26.0      0      0   7.9250         1
3       1  female  35.0      1      0  53.1000         1
4       3    male  35.0      0      0   8.0500         0
5       3    male  28.0      0      0   8.4583         0
6       1    male  54.0      0      0  51.8625         0
7       3    male   2.0      3      1  21.0750         0
8       3  female  27.0      0      2  11.1333         1
9       2  female  14.0      1      0  30.0708         1

## 문자 데이터를 숫자로 변환 --> 레이블 인코딩 --> 남:0, 여:1

In [14]:
df_model['age'] = df_model['sex'].map({'male':0, 'female':'1'})

In [15]:
df_model.head()

   pclass     sex age  sibsp  parch     fare  survived
0       3    male   0      1      0   7.2500         0
1       1  female   1      1      0  71.2833         1
2       3  female   1      0      0   7.9250         1
3       1  female   1      1      0  53.1000         1
4       3    male   0      0      0   8.0500         0

In [16]:
X = df_model[features] # 입력(특성, 피쳐)
y = df_model['survived'] # 정답(타겟)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

## 모델 학습

In [19]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [20]:
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'male'

## 예측

In [21]:
y_pred = model.predict(X_test)

AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'

## 정확도

In [22]:
accuracy_score(y_test, y_pred)

NameError: name 'y_pred' is not defined

## 분류 레포트

In [23]:
classification_report(y_test, y_pred, target_names=['사망', '생존'])

NameError: name 'y_pred' is not defined